version: '3'
services:
  nginx:
    container_name: provectus-nginx
    image: nginx:1.17
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - teste-iglu-app

  teste-iglu-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: java-teste-iglu:latest
    expose:
      - "8080"